services:
  app:
    build:
      context: .
      dockerfile: .ci/docker/Dockerfile
      target: deps
    image: vrf_ru-dev
    container_name: vrf_ru-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - "NEXT_TELEMETRY_DISABLED=1"
      - "PORT=3000"
      - "NODE_ENV=development"
      - "HOSTNAME=0.0.0.0"
      - "URL=http://localhost:3000/"
    working_dir: /app
    command: sh -c "echo 'Wait. Starting up. Running npm install...' && npm install && npm run dev"
    restart: always
    ports:
      - 3000:3000
